[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
IncompleteLU = "40713840-3770-5561-ab4c-a76e7d0d7895"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MatrixDepot = "b51810bb-c9f3-55da-ae3c-350fc1fbce05"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Preconditioners = "af69fa37-3177-5a40-98ee-561f696e4fcd"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
